export const font = {
  AvenirNextRegular: 'AvenirNextCyr-Regular',
  AvenirNextMedium: 'AvenirNextCyr-Medium',
  AvenirNextExtraBold: 'AvenirNextCyr-Heavy',
  AvenirNextSemiBold: 'AvenirNextCyr-Demi',
  AvenirNextBold: 'AvenirNextCyr-Bold',
  DMSansBold: 'DMSans-Bold',
  DMSansRegular: 'DMSans-Regular',
  DMSansMedium: 'DMSans-Medium',
  DMSansSemiBold: 'DMSans-SemiBold',
  DMSansExtraBold: 'DMSans-ExtraBold',
  QuicksandBold: 'Quicksand-Bold',
  QuicksandRegular: 'Quicksand-Regular',
  QuicksandMedium: 'Quicksand-Medium',
  QuicksandLight: 'Quicksand-Light',
  QuicksandSemiBold: 'Quicksand-SemiBold',
};
